added $(class)s_ to the related name of sections in content base
fixes
Error: One or more models did not validate:
content.content: Accessor for m2m field 'sections' clashes with related
m2m field 'Section.alternates'. Add a related_name argument to the
definition for 'sections'.
content.content: Reverse query name for m2m field 'sections' clashes
with related m2m field 'Section.alternates'. Add a related_name argument
to the definition for 'sections'.
audio.audiopublication: Accessor for m2m field 'sections' clashes with
related m2m field 'Section.alternates'. Add a related_name argument to
the definition for 'sections'.
audio.audiopublication: Reverse query name for m2m field 'sections'
clashes with related m2m field 'Section.alternates'. Add a related_name
argument to the definition for 'sections'.

when subclassing ContentBase